
export const images = [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmpa-OPGCHyX-GPQRrwoR289o79lh94R-ERw&s',
    'https://img.freepik.com/free-photo/painting-mountain-lake-with-mountain-background_188544-9126.jpg',
    'https://images8.alphacoders.com/136/thumb-350-1363709.webp',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYL6nIvJP72d-YQO2iUXcwZfh8875iKYUyTg&s',
];

export const productDetail = {
    name: 'L-Glutathione - for Skin Brightening and Antioxidant Support',
    originalPrice: 1498,
    salePrice: 953,
    onestar: 42,
    twostar: 0,
    threestar: 18,
    fourstar: 35,
    fivestar: 57,
    imageOne: 'https://herbalmax.in/cdn/shop/files/1st-image-color-background-l_glutathione_1.png?v=1731665236&width=823',
    imageTwo: 'https://herbalmax.in/cdn/shop/files/710u_e-myWL._SL1500_d5ce55f8-708e-4cf6-b3e6-61d8cb83889a.png?v=1731665232&width=823',
    imageThree: 'https://herbalmax.in/cdn/shop/files/60-l-glutathione-tablet-for-glowing-skin-reduce-pigmentation-for-original-imah3abwqhztgtp3.jpg?v=1731665236&width=823',
    imageFour: 'https://herbalmax.in/cdn/shop/files/71z4kkYfsuL._SL1500_9b73925c-bcca-44a7-892f-2e8119492a22.png?v=1731665232&width=823',
    imageFive: 'https://herbalmax.in/cdn/shop/files/last_6657254ff358b.jpg?v=1731665229&width=823',
    productId: 'sgrehkliulrhtbtr',
    info: 'Vitamin B12 Capsules are designed to support your daily energy levels and mental focus. Each easy-to-swallow capsule provides essential nutrients, including Vitamin B12, which may help you maintain a more vibrant, energetic lifestyle. Simple, effective, and easy to incorporate into your routine.',
};

export const products = [ 
    {
        name: '3Pcs Modern Abstract Wall Art Home Decor Rainbow Art Print Canvas Painting Geometric Poster Neutral Boho Wall Pictures 50X70Cm No Frame',
        category: 'Printed Canvas',
        originalPrice: 1498,
        salePrice: 953,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'sgrehkliulrhtbtr',
    },
    {
        name: 'Vintage Floral Botanical Prints Set of 3 Wall Art Flower Painting for Bedroom and Living Room Decor',
        category: 'Printed Canvas',
        originalPrice: 1799,
        salePrice: 1250,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'dhw7823nhjwebfk',
    },
    {
        name: 'Abstract Modern Line Art Poster Minimalist Black and White Wall Picture for Office Decor 40X60Cm No Frame',
        category: 'Printed Canvas',
        originalPrice: 1299,
        salePrice: 899,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'gy3woplbdszx93k',
    },
    {
        name: '5-Piece Cityscape Canvas Wall Art Set for Living Room with Vibrant Colors and Modern Design',
        category: 'Multi-Panel Canvas',
        originalPrice: 2999,
        salePrice: 2199,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'htbx3749cbrfwiqe',
    },
    {
        name: 'Boho Style Abstract Sun and Moon Wall Art Print Set of 2 for Bedroom and Nursery',
        category: 'Printed Canvas',
        originalPrice: 1499,
        salePrice: 1020,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'ncxqpwo3478xyuhf',
    },
    {
        name: 'Scandinavian Forest Scene Wall Art with Rustic Wooden Frame for Hallway Decor',
        category: 'Framed Art',
        originalPrice: 2499,
        salePrice: 1899,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'rbgfjql8392xmzow',
    },
    {
        name: '3D Metallic Flower Artwork with Textured Finish for Office and Home Decoration',
        category: 'Metal Wall Art',
        originalPrice: 3499,
        salePrice: 2749,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'vxztbgfi3847eqjn',
    },
    {
        name: 'Classic Movie Poster Replica for Home Theatre Room - The Godfather',
        category: 'Poster',
        originalPrice: 799,
        salePrice: 599,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'kfmvghk2847zncpw',
    },
    {
        name: '3Pcs Modern Abstract Wall Art Home Decor Rainbow Art Print Canvas Painting Geometric Poster Neutral Boho Wall Pictures 50X70Cm No Frame',
        category: 'Printed Canvas',
        originalPrice: 1498,
        salePrice: 953,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'sgrehkytktyliulrhtbtr',
    },
    {
        name: 'Vintage Floral Botanical Prints Set of 3 Wall Art Flower Painting for Bedroom and Living Room Decor',
        category: 'Printed Canvas',
        originalPrice: 1799,
        salePrice: 1250,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'dhw782fjkj3nhjwebfk',
    },
    {
        name: 'Abstract Modern Line Art Poster Minimalist Black and White Wall Picture for Office Decor 40X60Cm No Frame',
        category: 'Printed Canvas',
        originalPrice: 1299,
        salePrice: 899,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'gy3wogjytplbdszx93k',
    },
    {
        name: '5-Piece Cityscape Canvas Wall Art Set for Living Room with Vibrant Colors and Modern Design',
        category: 'Multi-Panel Canvas',
        originalPrice: 2999,
        salePrice: 2199,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'htbxeryr3749cbrfwiqe',
    },
    {
        name: 'Boho Style Abstract Sun and Moon Wall Art Print Set of 2 for Bedroom and Nursery',
        category: 'Printed Canvas',
        originalPrice: 1499,
        salePrice: 1020,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'ncxqpwortw3478xyuhf',
    },
    {
        name: 'Scandinavian Forest Scene Wall Art with Rustic Wooden Frame for Hallway Decor',
        category: 'Framed Art',
        originalPrice: 2499,
        salePrice: 1899,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'rbgfjql839tr2xmzow',
    },
    {
        name: '3D Metallic Flower Artwork with Textured Finish for Office and Home Decoration',
        category: 'Metal Wall Art',
        originalPrice: 3499,
        salePrice: 2749,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'vxztbgfi3fhf847eqjn',
    },
    {
        name: 'Classic Movie Poster Replica for Home Theatre Room - The Godfather',
        category: 'Poster',
        originalPrice: 799,
        salePrice: 599,
        image: 'https://bestpricearts.com/wp-content/uploads/2023/08/61Pq5E-AxcL._AC_SL1000_-300x300.jpg',
        productId: 'kfmvghk2847zdncpw',
    },
];