import React, { Fragment } from 'react';
import { Helmet } from 'react-helmet-async';

const Term = () => {
    return (
        <Fragment>
            <Helmet>
                <title>Terms And Conditions | Slasa - Embrace Wellness, Naturally</title>
                <meta name="description" content="Discover the power of nature with Slasa. Your trusted source for herbal remedies, wellness products, and holistic health solutions crafted with care and authenticity. Embrace a healthier, natural lifestyle today." />
                <link rel="canonical" href="https://herbaljivan.netlify.app/terms-and-conditions" />
            </Helmet>

            <section className='pageTwo flexcol center'>

                <div className='bg-gray-shadow text'>

                    <article><h1 className='heading'>Terms And Conditions</h1></article>

                    <p className='text'>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

                    <p className='text'>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name \[www.flipkart.com\] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)  </p>

                    <p className='text'>The Platform is owned by Flipkart Internet Private Limited, a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India (hereinafter referred to as "Flipkart").</p>

                    <p className='text'>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

                    <p className='text'>For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Flipkart allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Flipkart Internet Private Limited.</p>



                    <ul >
                        <p className='text'>Buyer needs to raise the replacement request within the return period applicable to the respective product. Once Buyer has raised a replacement request by contacting Us on the Toll Free Number provided on the Platform. Once the replacement request has been raised, the following steps shall be followed:</p>
                        <li className='text'>Buyer is asked for "Reason for Return". Among others, the following are the leading reasons:</li>
                        <li className='text'>Shipping was damaged</li>
                        <li className='text'>Item was defective  </li>
                        <li className='text'>Item Dead on Arrival</li>
                        <li className='text'>Item(s) were missing</li>
                        <li className='text'>In case the Seller accepts the replacement request, Buyer shall be required to return the product to the Seller and only after return of the product, Seller shall be obliged to provide the replacement product to the Buyer.                        </li>
                    </ul>

                    <ul >
                        <p className='text'>Buyer needs to raise the replacement request within the return period applicable to the respective product. Once Buyer has raised a replacement request by contacting Us on the Toll Free Number provided on the Platform. Once the replacement request has been raised, the following steps shall be followed:</p>
                        <li className='text'>Buyer is asked for "Reason for Return". Among others, the following are the leading reasons:</li>
                        <li className='text'>Shipping was damaged</li>
                        <li className='text'>Item was defective  </li>
                        <li className='text'>Item Dead on Arrival</li>
                        <li className='text'>Item(s) were missing</li>
                        <li className='text'>In case the Seller accepts the replacement request, Buyer shall be required to return the product to the Seller and only after return of the product, Seller shall be obliged to provide the replacement product to the Buyer.                        </li>
                    </ul>
                </div>


            </section>
        </Fragment>
    )
}

export default Term